# Generated by Django 3.1.1 on 2020-09-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancost',
            name='plan',
        ),
        migrations.AddField(
            model_name='plancost',
            name='plans',
            field=models.ManyToManyField(help_text='the subscription plan for these cost details', related_name='costs', to='subscriptions.SubscriptionPlan'),
        ),
    ]
