# Generated by Django 3.1.1 on 2020-10-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20200930_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='subscription',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan_cost',
            field=models.ForeignKey(help_text='the plan costs and billing frequency for this user subscription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plancost'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(help_text='the subscription plan for this user subscription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='the subscription plan for these cost details', null=True, related_name='costs', to='subscriptions.SubscriptionPlan'),
        ),
    ]
